app:
  name: BlockWord
  runType: dev

httpServer:
  open: true
  prod: 11231

grpcServer:
  open: true
  prod: 11232
  log: true

redis:
  host: 192.168.0.197
  port: 6379
  db: 4
  password: love0021$%
  maxidle: 50
  maxactive: 10000

logCentre:
  host: 192.168.0.9
  prod: 22223