app:
  name: BlockWord
  runType: dev

httpServer:
  open: true
  prod: 1251

grpcServer:
  open: false
  prod: 1252
  log: true

tcpServer:
  open: true
  prod: 1253

udpServer:
  open: true
  prod: 1254

redis:
  host: 192.168.0.197
  port: 6379
  db: 4
  password: love0021$%
  maxidle: 50
  maxactive: 10000

mqType: rabbit

nsq:
  producer: 192.168.0.197:4150
  consumer: 192.168.0.197:4161

rabbit:
  addr: 192.168.0.191:5672/admin
  user: admin
  password: admin

kafka:
  addr: 192.168.0.191:9092