app:
  name: imghelper
  runType: dev

httpServer:
  open: true
  prod: 12361

grpcServer:
  open: true
  prod: 12362
  log: true

ttf: /ttf/Alibaba-PuHuiTi-Heavy.ttf

logCentre:
  host: 192.168.0.9
  prod: 22223