app:
  name: shortlink
  runType: dev

httpServer:
  open: true
  prod: 12333

grpcServer:
  open: true
  prod: 12334
  log: true

redis:
  host: 119.23.143.202
  port: 6379
  db: 3
  password:
  maxidle: 50
  maxactive: 10000

logCentre:
  host: 192.168.0.9
  prod: 22223


