app:
  name: ShortLink
  runType: dev

httpServer:
  open: true
  prod: 1233

grpcServer:
  open: true
  prod: 1234
  log: true

redis:
  host: 192.168.0.197
  port: 6379
  db: 4
  password: love0021$%
  maxidle: 50
  maxactive: 10000